CREATE TABLE users(
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	gmail VARCHAR(100) UNIQUE NOT NULL,
	password VARCHAR(50) NOT NULL
);
CREATE TABLE products(
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	description TEXT NOT NULL,
	price NUMERIC(10,2), 
	stock INTEGER NOT NULL
);
CREATE TABLE orders(
	id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
	total_price NUMERIC(10,2) NOT NULL
);
CREATE TABLE order_items(
	id SERIAL PRIMARY KEY,
	order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE ,
	product_id INTEGER REFERENCES products(id) ,
	quantity INTEGER NOT NULL,
	price NUMERIC(10,2) NOT NULL
);