--SQL FULLY JOIN 
SELECT BOOK.Title, BOOK_LOANS.Date_out, BOOK_LOANS.Due_date, LIBRARY_BRANCH.Branch_name
FROM BOOK
FULL JOIN BOOK_LOANS ON BOOK.Book_id = BOOK_LOANS.Book_id
FULL JOIN LIBRARY_BRANCH ON BOOK_LOANS.Branch_id = LIBRARY_BRANCH.Branch_id
ORDER BY BOOK.Title, LIBRARY_BRANCH.Branch_name;

