SELECT BOOK.Title, BOOK_AUTHORS.Author_name, PUBLISHER.Name
FROM BOOK
INNER JOIN BOOK_AUTHORS ON BOOK.Book_id = BOOK_AUTHORS.Book_id
INNER JOIN PUBLISHER ON BOOK.Publisher_name = PUBLISHER.Name

WHERE PUBLISHER.Address LIKE '%New York%' ORDER BY BOOK.Title;


--SQL INNER JOIN 