SELECT LIBRARY_BRANCH.Branch_name, COUNT(BOOK_LOANS.Card_no) AS Num_Borrowers
FROM LIBRARY_BRANCH
LEFT JOIN BOOK_LOANS ON LIBRARY_BRANCH.Branch_id = BOOK_LOANS.Branch_id
GROUP BY LIBRARY_BRANCH.Branch_name
ORDER BY Num_Borrowers DESC;

--SQL LEFT JOIN