--SQL RIGHT JOIN 
SELECT BOOK.Title, BOOK_COPIES.No_of_copies, LIBRARY_BRANCH.Branch_name
FROM BOOK_COPIES
RIGHT JOIN BOOK ON BOOK_COPIES.Book_id = BOOK.Book_id
LEFT JOIN LIBRARY_BRANCH ON BOOK_COPIES.Branch_id = LIBRARY_BRANCH.Branch_id
ORDER BY BOOK.Title, LIBRARY_BRANCH.Branch_name;

