SELECT BRANCH.branch_name, BOOK_COPIES.no_of_copies
FROM BOOK_COPIES
INNER JOIN BOOK ON BOOK_COPIES.book_id = BOOK.book_id
INNER JOIN LIBRARY_BRANCH BRANCH ON BOOK_COPIES.branch_id = BRANCH.branch_id
WHERE BOOK.title = 'ABC';
