SELECT BOOK_LOANS.book_id, BOOK.title, BOOK_LOANS.date_out, BOOK_LOANS.due_date, LIBRARY_BRANCH.branch_name
FROM BOOK_LOANS
INNER JOIN BOOK ON BOOK_LOANS.book_id = BOOK.book_id
INNER JOIN LIBRARY_BRANCH ON BOOK_LOANS.branch_id = LIBRARY_BRANCH.branch_id
WHERE BOOK_LOANS.date_out < '2023-01-01';
