SELECT LIBRARY_BRANCH.Branch_id, LIBRARY_BRANCH.Branch_name, SUM(BOOK_COPIES.No_of_copies) AS Total_Books
FROM LIBRARY_BRANCH
JOIN BOOK_COPIES ON BOOK_COPIES.Branch_id = LIBRARY_BRANCH.Branch_id
GROUP BY LIBRARY_BRANCH.Branch_id;
